#########################################
# The "production" compose file builds 
# on your EC2 instance
#########################################

version: "3"
services:
  nginx:
    image: $DOCKERHUB_UNAME/juniordev-webserver-prod:$NEW_VERSION
    restart: always
    ports:
      - "80:80"
volumes:
  postgres_data: