services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: >
      sh -c "until PGPASSWORD=$POSTGRES_PASSWORD psql -h db -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1' > /dev/null 2>&1; do echo 'Waiting for database...'; sleep 2; done &&
             echo 'Database is ready! Running migrations...' &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             echo 'Starting Gunicorn...' &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 backend.wsgi:application"
  
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: