# version: '3.8'

services:
  web:
    build: .
    command: bash -c "./run_compose.sh"
    volumes:
      - .:/app
    env_file:
      - .env  
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - FINDWORK_API_KEY=${FINDWORK_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: postgres_container_jobs_app
    env_file:
      - .env  
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
