# Generated by Django 5.1.7 on 2025-03-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearch',
            name='location',
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='job_url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
